name: deploy-container

on:
  push:
    branches:
      - master
    paths:
      - packages/container/**

defaults:
  run:
    working-directory: packages/container

jobs:
  build:
    runs-on: ubuntu-latest
    container: node:14.11.0-buster
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Intasll deps and build
        run: yarn && yarn build
      - run: apt update && apt -y install python3 python3-pip
        shell: bash
      - run: pip3 install awscli
        shell: bash
      - name: Syndc build with aws
        run: aws s3 sync dist s3://${{ secrets.AWS_S3_BUCKET_NAME }}/container/latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - name: Invalidation
        run: aws cloudfront create-invalidation --distribution-id E3CUJMI6LN3J3L --paths '/container/latest/index.html'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}



